package dependencyVersions


object DependencyVersions {
    const val ACTIVITY_VERSION = "1.2.3"
    const val APPCOMPAT_VERSION = "1.2.0"
    const val COIL_VERSION = "1.2.1"
    const val CONSTRAINTLAYOUT_VERSION = "2.0.4"
    const val COORDINATORLAYOT_VERSION = "1.1.0"
    const val CORE_VERSION = "1.3.2"
    const val COROUTINES_VERSION = "1.4.3"
    const val DATASTORE_VERSION = "1.0.0-beta01"
    const val FRAG_VERSION = "1.3.3"
    const val HILT_VERSION = "2.35.1"
    const val JSOUP_VERSION = "1.13.1"
    const val KOTLIN_VERSION = "1.4.32"
    const val LIFECYCLE_VERSION = "2.3.1"
    const val MATERIAL_VERSION = "1.3.0"
    const val MOSHI_VERSION = "1.12.0"
    const val NAV_VERSION = "2.3.5"
    const val OKHTTP3_VERSION = "4.9.1"
    const val PAGING_VERSION = "3.0.0"
    const val RECYCLERVIEW_VERSION = "1.2.0"
    const val RETROFIT2_VERSION = "2.9.0"
    const val ROOM_VERSION = "2.3.0-rc01"
    const val SHIMMER_VERSION = "0.5.0"
    const val SHIMMER_RECYCLER_VERSION = "0.4.1"
    const val TIMBER_VERSION = "4.7.1"
    const val VIEWPAGER2_VERSION = "1.0.0"
}
