name: Build

on:
  # Trigger on every push to any branch except for master branch.
  push:
    branches:
      - '*'
      - '!master'

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Notify on Slack
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
